functions:
  'test':
    command: shell.exec
    params:
      working_dir: src
      shell: bash
      script: |
        source ~/.rvm/scripts/rvm
        rvm install ruby-2.3.0
        rvm use 2.3.0
        gem install bundler
        bundle install
        bundle exec rake clean
        bundle exec rake compile
        bundle exec rake spec

tasks:
  - name: 'build'
    commands:
      - command: git.get_project
        params:
          directory: src
      - func: 'test'

buildvariants:
  - name: debian
    display_name: Debian 8.1 x86
    run_on:
      - debian81-test
    tasks:
      - name: 'build'
  - name: rhelzseries
    display_name: RHEL 7.2 Z-Series
    run_on:
      - rhel72-zseries-test
    tasks:
      - name: 'build'
  - name: rhelpower
    display_name: RHEL 7.1 PowerPC
    run_on:
      - rhel71-power8-test
    tasks:
      - name: 'build'
